### ISSUE TITLE
评论问题

### ISSUE THREAD

**Issue by Jiwangsheng** [the1812/Bilibili-Evolved#1103] opened 2020-10-28 13:11 UTC
再收藏里打开视频，评论区会消失。关掉脚本后评论区恢复正常

**Comment by Coulomb-G** [comment] 2020-10-28 13:12
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)

**Closed** 2020-10-28 13:12 UTC
Labels: duplicate
