### ISSUE TITLE
点赞时需要登录，登录后还要登录

### ISSUE THREAD

**Issue by Wdam** [the1812/Bilibili-Evolved#1098] opened 2020-10-28 11:54 UTC
版本Stable v1.11.0
点赞投币收藏都提示登录
![image](https://user-images.githubusercontent.com/42366809/97432732-63137200-1957-11eb-9c8b-455668c990d0.png)

视频https://www.bilibili.com/video/av457582842

**Comment by Coulomb-G** [comment] 2020-10-28 11:55
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)

**Closed** 2020-10-28 11:56 UTC
Labels: duplicate
