### ISSUE TITLE
评论区和视频推荐白色，看不了

### ISSUE THREAD

**Issue by bige47** [the1812/Bilibili-Evolved#1082] opened 2020-10-28 08:38 UTC
**附加截图**
![B41VV%ZDUHO CWS~ OAP9$5](https://user-images.githubusercontent.com/50322735/97411954-cfab5400-18f8-11eb-9798-c59de0b07060.png)

**Comment by SnowMeteors** [comment] 2020-10-28 08:46
我也是

**Comment by Coulomb-G** [comment] 2020-10-28 08:49
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)

**Closed** 2020-10-28 08:50 UTC
Labels: duplicate
