### ISSUE TITLE
评论区、UP 主头像和相关推荐视频的封面全都无法加载，在已经登录的情况下点赞、投币或收藏时会弹出登录框

### ISSUE THREAD

**Issue by ChurchEChan** [the1812/Bilibili-Evolved#1105] opened 2020-10-28 13:27 UTC
**关于哪一项功能**
* 点赞/投币/收藏工具栏
* 评论区
* 图片缓存

**问题描述**

在任意视频中（此处以 https://www.bilibili.com/video/av542620447 为例），评论区无法加载，UP 主的头像和相关推荐视频的封面全部无法加载。
并且点击点赞、投币或收藏时会提示登录，尽管此时已经登录了，仍会弹出登录框。
在弹出的登录框中登录账号并完成验证，登录框消失，点赞、投币或收藏未完成，再次点击点赞、投币或收藏时登录框再次出现。

**脚本版本**

Stable v1.11.0
内容包: 029ae6d

**浏览器版本**

Chrome 86.0.4240.75（正式版本） （64 位）

**错误信息**

`
stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:40898)
    at p (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:57231)
    at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:56494
    at f (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:56726)
    at h (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:57317)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:60655)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:60590)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:60590)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:61055)
    at a.t._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:34369)
hn.get @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7
hn @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7
(anonymous) @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7
Tn.$mount @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7
Tn.$mount @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7
(anonymous) @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:46
fo.onReady @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:46
So.onReady @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:46
(anonymous) @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:46
n @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:1
(anonymous) @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:32
n @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:1
(anonymous) @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:1
(anonymous) @ stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:1
`

**附加截图**
![image](https://user-images.githubusercontent.com/40969931/97441652-eaff7900-1963-11eb-9d22-74f8cd466065.png)
![image](https://user-images.githubusercontent.com/40969931/97441706-f783d180-1963-11eb-86a8-b14c53cbb1cb.png)

**Comment by Coulomb-G** [comment] 2020-10-28 13:28
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)

**Closed** 2020-10-28 13:28 UTC
Labels: duplicate
