### ISSUE TITLE
为什么播放视频，旁边的推荐视频没有封面，评论也没了，我实在是找不到相关设置，才来打扰

### ISSUE THREAD

**Issue by Hzmaaa** [the1812/Bilibili-Evolved#1087] opened 2020-10-28 10:10 UTC
![K}I~FW`$W){UXBQ)~2SJV%2](https://user-images.githubusercontent.com/73585448/97420361-2db25880-1946-11eb-9df2-5596825b5cd2.png)

**Comment by Coulomb-G** [comment] 2020-10-28 10:10
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)

**Closed** 2020-10-28 10:13 UTC
Labels: duplicate

**Comment by Hzmaaa** [comment] 2020-10-28 10:17
> 解决方法见[#1076(评论)](https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480)
> (复本)#1076)

感谢
