### ISSUE TITLE
评论区加载不出来

### ISSUE THREAD

**Issue by ty666ty** [the1812/Bilibili-Evolved#1088] opened 2020-10-28 10:20 UTC

**Comment by Geeyun-JY3** [comment] 2020-10-28 10:24
看
置
顶
#1076

**Comment by the1812** [comment] 2020-10-28 10:24
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)

**Closed** 2020-10-28 10:24 UTC
Labels: bad-issue, duplicate

**Comment by the1812** [comment] 2020-10-28 10:34
@Geeyun-JY3 你也可以整个 [Saved reply](https://github.com/settings/replies), 一键回复这几天的 duplicate (

**Comment by Geeyun-JY3** [comment] 2020-10-28 10:38
> 你也可以整个 [Saved reply](https://github.com/settings/replies), 一键回复这几天的 duplicate (

23333 好主意（
