### ISSUE TITLE
开脚本不加载评论

### ISSUE THREAD

**Issue by yyzzm-ly** [the1812/Bilibili-Evolved#1126] opened 2020-10-29 11:07 UTC
**关于哪一项功能**

**问题描述**

**脚本版本**
例如正式版1.11.0

**浏览器版本**

**错误信息**

![图片](https://user-images.githubusercontent.com/69896425/97560460-a6ceb000-1a19-11eb-8500-8aaebfd88acf.png)
------------------------------------

downloadable font: font load failed (font-family: "Material Design Icons" style:normal weight:400 stretch:100 src index:0): status=2152398858 source: data:font/woff2;base64,d09GMgABAAAAAvIwAAoAAAAIVvwAAvHfAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAABlYAgwIKm+RslrF7C/NEAAE2AiQD80AEIAWFMgeD1 … VEpETDS0rXTv8ng+hlM2lvXy5bw4xOXL41qEds/Ive8ZejODli/WoKiW8meF3MppPIrLlPjE0so6xws+3Ve/jWVZvsjhs8lWYhS32071ESp9qOQkRVGW4chf9d8AAA==      

---------------------------------
Uncaught DOMException: Node.appendChild: Cannot add children to a Text stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    appendChild https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    p https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    f https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    f https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    h https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    P https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    P https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    P https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    Zi https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    _update https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    r https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    get https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    hn https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    mount https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    $mount https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    $mount https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    init https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    P https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    P https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    P https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    P https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    Zi https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    _update https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    r https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    get https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    hn https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    mount https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    $mount https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    $mount https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    init https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    P https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    Zi https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    _update https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    r https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    get https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    hn https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    mount https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    $mount https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    $mount https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:7
    <anonymous> https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:46
    onReady https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:46
    onReady https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:46
    <anonymous> https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:46
    n https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:1
    <anonymous> https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:32
    n https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:1
    <anonymous> https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:1
    <anonymous> https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.b1893ec27402a1f3930a7742957efa396edabfac.js:1
---------------------------------

**附加截图**
![图片](https://user-images.githubusercontent.com/69896425/97559783-d92bdd80-1a18-11eb-88e4-973439f72b97.png)
![图片](https://user-images.githubusercontent.com/69896425/97559857-ef399e00-1a18-11eb-993b-415ca324a3e1.png)

**Comment by Coulomb-G** [comment] 2020-10-29 11:08
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)

**Closed** 2020-10-29 11:08 UTC
Labels: duplicate
