### ISSUE TITLE
启动插件后投币出现bug

### ISSUE THREAD

**Issue by asgh215** [the1812/Bilibili-Evolved#1124] opened 2020-10-29 09:16 UTC
**关于哪一项功能**
投币功能

**问题描述**
在登录状态下启动插件后按投币按钮弹出登录窗口，且在该窗口登录后依然会弹出，多个视频页面中均出现这个问题

**脚本版本**
正式版1.11.0

**浏览器版本**
Microsoft Edge  86.0.622.51

**错误信息**
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:40898)
    at p (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:57231)
    at https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:56494
    at f (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:56726)
    at h (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:57317)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:60655)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:60590)
    at P (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:60590)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:61055)
    at a.t._update (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.e511bce03d58122c9b3878d2b6bc91afa2d5d4c9.js:7:34369)

**附加截图**
![QQ图片20201029171132](https://user-images.githubusercontent.com/49670081/97548676-64ea3d80-1a0a-11eb-8827-602f322835fd.png)

**Comment by the1812** [comment] 2020-10-29 09:29
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)

**Closed** 2020-11-19 11:38 UTC
Labels: duplicate
