### ISSUE TITLE
评论区无法打开

### ISSUE THREAD

**Issue by skld315** [the1812/Bilibili-Evolved#1129] opened 2020-10-29 12:42 UTC
如题，不晓得为什么

![image](https://user-images.githubusercontent.com/45231589/97575103-30d14580-1a27-11eb-9e45-d84fae8b0f93.png)

![image](https://user-images.githubusercontent.com/45231589/97575029-139c7700-1a27-11eb-86a3-dc2406821077.png)

**Comment by Coulomb-G** [comment] 2020-10-29 12:43
解决方法见 https://github.com/the1812/Bilibili-Evolved/issues/1076#issuecomment-717691480
(Duplicate of #1076)

**Closed** 2020-11-19 11:38 UTC
Labels: duplicate
